/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    input [34:0] red,
    input [34:0] green,
    output reg [6:0] r_red,
    output reg [4:0] c_red,
    output reg [6:0] r_green,
    output reg [4:0] c_green
  );
  
  
  
  localparam FLIP = 5'h10;
  
  wire [3-1:0] M_counter_r_value;
  counter_24 counter_r (
    .clk(clk),
    .rst(rst),
    .value(M_counter_r_value)
  );
  
  reg [2:0] whichrow;
  
  integer i;
  
  always @* begin
    r_red = 7'h00;
    c_red = 5'h1f;
    r_green = 7'h00;
    c_green = 5'h1f;
    whichrow = M_counter_r_value;
    r_red[(whichrow)*1+0-:1] = 1'h1;
    r_green[(whichrow)*1+0-:1] = 1'h1;
    for (i = 1'h0; i <= 3'h4; i = i + 1) begin
      c_red[(i)*1+0-:1] = ~red[(i)*7+(3'h6 - whichrow)*1+0-:1];
      c_green[(i)*1+0-:1] = ~green[(i)*7+(3'h6 - whichrow)*1+0-:1];
    end
  end
endmodule
