/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_20 (
    input [5:0] number,
    output reg [34:0] map_mine,
    output reg [34:0] map_bonus,
    output reg [2:0] start_row,
    output reg [2:0] start_col,
    output reg [2:0] end_row,
    output reg [2:0] end_col,
    output reg [2:0] bound_left,
    output reg [2:0] bound_right,
    output reg [2:0] bound_up,
    output reg [2:0] bount_down,
    output reg [34:0] boundary
  );
  
  
  
  always @* begin
    boundary = 35'h7f83060c1;
    if (number < 6'h20) begin
      bound_left = 3'h5;
      bound_right = 1'h1;
      bound_up = 2'h3;
      bount_down = 1'h0;
    end else begin
      bound_left = 3'h6;
      bound_right = 1'h0;
      bound_up = 3'h4;
      bount_down = 1'h0;
    end
    
    case (number)
      1'h0: begin
        map_bonus = 35'h000000004;
        map_mine = 35'h001040100;
        start_row = 2'h3;
        start_col = 3'h4;
        end_row = 2'h3;
        end_col = 2'h2;
      end
      1'h1: begin
        map_bonus = 35'h000080000;
        map_mine = 35'h001000902;
        start_row = 2'h2;
        start_col = 2'h3;
        end_row = 1'h0;
        end_col = 3'h5;
      end
      2'h2: begin
        map_bonus = 35'h000001000;
        map_mine = 35'b000000001000000000x0000000000110000;
        start_row = 1'h0;
        start_col = 1'h1;
        end_row = 2'h3;
        end_col = 2'h2;
      end
      2'h3: begin
        map_bonus = 35'h000000020;
        map_mine = 35'h001420800;
        start_row = 1'h1;
        start_col = 2'h3;
        end_row = 2'h2;
        end_col = 3'h4;
      end
      3'h4: begin
        map_bonus = 35'h000000400;
        map_mine = 35'h000088200;
        start_row = 1'h1;
        start_col = 3'h5;
        end_row = 2'h2;
        end_col = 2'h2;
      end
      3'h5: begin
        map_bonus = 35'h000020000;
        map_mine = 35'h006001200;
        start_row = 2'h2;
        start_col = 3'h4;
        end_row = 1'h0;
        end_col = 2'h2;
      end
      3'h6: begin
        map_bonus = 35'h000000020;
        map_mine = 35'h000910000;
        start_row = 2'h3;
        start_col = 3'h4;
        end_row = 1'h1;
        end_col = 3'h5;
      end
      3'h7: begin
        map_bonus = 35'h000020000;
        map_mine = 35'h006001000;
        start_row = 2'h2;
        start_col = 3'h5;
        end_row = 1'h0;
        end_col = 2'h3;
      end
      4'h8: begin
        map_bonus = 35'h000000100;
        map_mine = 35'h000820020;
        start_row = 2'h2;
        start_col = 3'h5;
        end_row = 2'h2;
        end_col = 1'h1;
      end
      4'h9: begin
        map_bonus = 35'h000020000;
        map_mine = 35'h006000800;
        start_row = 2'h3;
        start_col = 1'h1;
        end_row = 1'h0;
        end_col = 1'h1;
      end
      4'ha: begin
        map_bonus = 35'h000000020;
        map_mine = 35'h001020008;
        start_row = 2'h2;
        start_col = 1'h1;
        end_row = 2'h2;
        end_col = 3'h5;
      end
      4'hb: begin
        map_bonus = 35'h000000004;
        map_mine = 35'h002008020;
        start_row = 2'h2;
        start_col = 3'h5;
        end_row = 2'h3;
        end_col = 2'h2;
      end
      4'hc: begin
        map_bonus = 35'h000080000;
        map_mine = 35'h002001408;
        start_row = 2'h3;
        start_col = 3'h5;
        end_row = 1'h1;
        end_col = 2'h2;
      end
      4'hd: begin
        map_bonus = 35'h000000020;
        map_mine = 35'h004040200;
        start_row = 1'h1;
        start_col = 2'h3;
        end_row = 2'h2;
        end_col = 3'h5;
      end
      4'he: begin
        map_bonus = 35'h000000200;
        map_mine = 35'h001011800;
        start_row = 2'h3;
        start_col = 3'h4;
        end_row = 2'h2;
        end_col = 1'h1;
      end
      4'hf: begin
        map_bonus = 35'h000000004;
        map_mine = 35'h001010002;
        start_row = 2'h3;
        start_col = 3'h5;
        end_row = 2'h3;
        end_col = 1'h1;
      end
      5'h10: begin
        map_bonus = 35'h000020000;
        map_mine = 35'h002040000;
        start_row = 1'h0;
        start_col = 3'h5;
        end_row = 2'h3;
        end_col = 1'h1;
      end
      6'h20: begin
        map_bonus = 35'h040002000;
        map_mine = 35'h400421800;
        start_row = 3'h4;
        start_col = 2'h3;
        end_row = 1'h0;
        end_col = 2'h3;
      end
      6'h21: begin
        map_bonus = 35'h008800000;
        map_mine = 35'h204048800;
        start_row = 3'h4;
        start_col = 3'h6;
        end_row = 3'h4;
        end_col = 2'h2;
      end
      6'h22: begin
        map_bonus = 35'h000801000;
        map_mine = 35'h101088020;
        start_row = 1'h0;
        start_col = 2'h2;
        end_row = 2'h3;
        end_col = 3'h4;
      end
      6'h23: begin
        map_bonus = 35'h000090000;
        map_mine = 35'h208840004;
        start_row = 3'h4;
        start_col = 2'h3;
        end_row = 1'h1;
        end_col = 3'h5;
      end
      6'h24: begin
        map_bonus = 35'h000001100;
        map_mine = 35'h600800060;
        start_row = 2'h2;
        start_col = 2'h3;
        end_row = 3'h4;
        end_col = 2'h2;
      end
      6'h25: begin
        map_bonus = 35'h200008000;
        map_mine = 35'h000881402;
        start_row = 1'h1;
        start_col = 2'h2;
        end_row = 2'h3;
        end_col = 3'h6;
      end
      6'h26: begin
        map_bonus = 35'h001000008;
        map_mine = 35'h48c000800;
        start_row = 1'h0;
        start_col = 3'h5;
        end_row = 2'h2;
        end_col = 2'h3;
      end
      6'h27: begin
        map_bonus = 35'h000801000;
        map_mine = 35'h140042070;
        start_row = 1'h0;
        start_col = 1'h0;
        end_row = 3'h4;
        end_col = 3'h5;
      end
      6'h28: begin
        map_bonus = 35'h020000100;
        map_mine = 35'h580800008;
        start_row = 3'h4;
        start_col = 2'h2;
        end_row = 2'h3;
        end_col = 3'h5;
      end
      6'h29: begin
        map_bonus = 35'h004000040;
        map_mine = 35'h0400a8800;
        start_row = 1'h0;
        start_col = 2'h2;
        end_row = 2'h3;
        end_col = 3'h4;
      end
      6'h2a: begin
        map_bonus = 35'h000000840;
        map_mine = 35'h008800411;
        start_row = 1'h0;
        start_col = 2'h3;
        end_row = 3'h4;
        end_col = 3'h6;
      end
      6'h2b: begin
        map_bonus = 35'h200000004;
        map_mine = 35'h520800400;
        start_row = 2'h2;
        start_col = 1'h0;
        end_row = 3'h4;
        end_col = 2'h3;
      end
      6'h2c: begin
        map_bonus = 35'h000021000;
        map_mine = 35'h00440020c;
        start_row = 2'h2;
        start_col = 3'h4;
        end_row = 1'h0;
        end_col = 1'h0;
      end
      6'h2d: begin
        map_bonus = 35'h040000020;
        map_mine = 35'h009400048;
        start_row = 1'h0;
        start_col = 1'h1;
        end_row = 3'h4;
        end_col = 3'h6;
      end
      6'h2e: begin
        map_bonus = 35'h0a0000000;
        map_mine = 35'h04008000b;
        start_row = 3'h4;
        start_col = 3'h5;
        end_row = 1'h1;
        end_col = 2'h2;
      end
      6'h2f: begin
        map_bonus = 35'h000108000;
        map_mine = 35'h0420a1000;
        start_row = 3'h4;
        start_col = 1'h1;
        end_row = 1'h0;
        end_col = 1'h0;
      end
      default: begin
        map_bonus = 35'h000000000;
        map_mine = 35'h000000000;
        start_row = 1'h0;
        start_col = 1'h0;
        end_row = 1'h0;
        end_col = 1'h0;
      end
    endcase
  end
endmodule
