/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module numbers_21 (
    input [2:0] round,
    output reg [34:0] out
  );
  
  
  
  always @* begin
    
    case (round)
      1'h1: begin
        out = 35'h08302041c;
      end
      2'h2: begin
        out = 35'h1c087081c;
      end
      2'h3: begin
        out = 35'h1c087021c;
      end
      3'h4: begin
        out = 35'h142870204;
      end
      3'h5: begin
        out = 35'h1c207021c;
      end
      3'h6: begin
        out = 35'h102070a1c;
      end
      default: begin
        out = 35'h000000000;
      end
    endcase
  end
endmodule
