/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module animation_23 (
    input clk,
    input rst,
    output reg [34:0] out_mine,
    output reg [34:0] out_win
  );
  
  
  
  reg [129:0] mine;
  
  reg [199:0] win;
  
  localparam FLIP = 5'h18;
  
  wire [5-1:0] M_counter_mine_value;
  counter_37 counter_mine (
    .clk(clk),
    .rst(rst),
    .value(M_counter_mine_value)
  );
  
  wire [6-1:0] M_counter_win_value;
  counter_38 counter_win (
    .clk(clk),
    .rst(rst),
    .value(M_counter_win_value)
  );
  
  integer i;
  
  always @* begin
    mine = 130'h1b3a2e0924ca02492ae09249a024ba2e0;
    win = 200'h899224ba208a5224932052522492a02252249260218c1b3a20;
    for (i = 1'h0; i < 3'h5; i = i + 1) begin
      out_mine[(i)*7+6-:7] = mine[(i)*26+25-:26] << M_counter_mine_value | mine[(i)*26+25-:26] >> (5'h1a - M_counter_mine_value);
      out_win[(i)*7+6-:7] = win[(i)*40+39-:40] << M_counter_win_value | win[(i)*40+39-:40] >> (6'h28 - M_counter_win_value);
    end
  end
endmodule
