/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_digits_3 (
    input clk,
    input rst,
    input [13:0] scores,
    input [7:0] timeinp,
    output reg [7:0] digitout_score,
    output reg [3:0] selectdigit_score,
    output reg [7:0] digitout_time_ge,
    output reg [7:0] digitout_time_shi
  );
  
  
  
  localparam FLIP = 5'h10;
  
  wire [2-1:0] M_counter_score_value;
  counter_25 counter_score (
    .clk(clk),
    .rst(rst),
    .value(M_counter_score_value)
  );
  
  reg [15:0] raw_score;
  
  reg [11:0] raw_time;
  
  wire [16-1:0] M_convert1_digits;
  reg [14-1:0] M_convert1_value;
  bin_to_dec_26 convert1 (
    .value(M_convert1_value),
    .digits(M_convert1_digits)
  );
  
  wire [12-1:0] M_convert2_digits;
  reg [10-1:0] M_convert2_value;
  bin_to_dec_27 convert2 (
    .value(M_convert2_value),
    .digits(M_convert2_digits)
  );
  
  wire [7-1:0] M_numbers_score_segs;
  reg [4-1:0] M_numbers_score_char;
  seven_seg_28 numbers_score (
    .char(M_numbers_score_char),
    .segs(M_numbers_score_segs)
  );
  
  wire [7-1:0] M_numbers_time_ge_segs;
  reg [4-1:0] M_numbers_time_ge_char;
  seven_seg_28 numbers_time_ge (
    .char(M_numbers_time_ge_char),
    .segs(M_numbers_time_ge_segs)
  );
  
  wire [7-1:0] M_numbers_time_shi_segs;
  reg [4-1:0] M_numbers_time_shi_char;
  seven_seg_28 numbers_time_shi (
    .char(M_numbers_time_shi_char),
    .segs(M_numbers_time_shi_segs)
  );
  
  always @* begin
    digitout_score = 8'h00;
    selectdigit_score = 4'hf;
    digitout_time_ge = 8'h00;
    digitout_time_shi = 8'h00;
    M_convert1_value = scores;
    M_convert2_value = timeinp;
    raw_score = M_convert1_digits;
    raw_time = M_convert2_digits;
    M_numbers_score_char = raw_score[(M_counter_score_value)*4+3-:4];
    digitout_score[0+6-:7] = M_numbers_score_segs;
    selectdigit_score[(M_counter_score_value)*1+0-:1] = 1'h0;
    M_numbers_time_ge_char = raw_time[4+3-:4];
    digitout_time_ge[0+6-:7] = M_numbers_time_ge_segs;
    M_numbers_time_shi_char = raw_time[8+3-:4];
    digitout_time_shi[0+6-:7] = M_numbers_time_shi_segs;
  end
endmodule
